{
    files: {
        camera_config: /workspace/oneVR/cam/gopro_hero_12/config.yaml,
        input_left: /workspace/data/left.mp4,
        input_right: /workspace/data/right.mp4,
        output_directory: /workspace/data/,
        output_composite: composite_3D_SBS_LR.mp4
    },
    output_settings: {
        width: 8192,
        height: 4096,
        unused_fps: 30     # default 29.97 fps if not specified
    },
    encode_settings: {
        hardware: gpu,     # gpu / cpu
        codec: hevc,       # hvec / h264
        preset: p4,        # p1...p7 (lowest...highest quality)
        cq: 23,            # <23 for higher quality
        crf: 18,           # <23 for higher quality
        bitrate: 40000000, # mbps
        gop: 60            # generally use 2xfps
    },
    sound_settings: {
        left_source: true,
        right_source: false
    }
}